// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("FCSInno")]
[assembly: AssemblyDescription("FCSInno")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Frede Hundewadt")]
[assembly: AssemblyProduct("FCSInno")]
[assembly: AssemblyCopyright("Copyright © FCS 2015-2020")]
[assembly: AssemblyTrademark("FCS © Innotec Danmark A/S")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]
[assembly: Guid("aaf08873-14e5-411d-8ec8-629782ac8f03")]

[assembly: AssemblyVersion("2.1.20289.1156")]
[assembly: AssemblyFileVersion("2.1.20289.1156")]